### ISSUE TITLE
Broken KWM link

### ISSUE THREAD

**Issue by advortsov** [knazarov/dotfiles#1]
Here:
Polybar-kwm is an Übersicht widget that tries to recreate the same behavior as polybar on macOS for kwm

**Comment by knazarov** [comment]
Yeah, that's because the README.md in that directory is taken from the widget author, that has created it in the times of KWM. Now KWM is deprecated in favor of yabai. Not sure what to do about it, to be honest. Maybe I really should fix the readme.

**Comment by knazarov** [comment]
Hi @advortsov,

I took my time to improve the widget (fix css and other small things), and update the README. Now you should be able to reuse it, if you so wish.
