### ISSUE TITLE
File missing usr/local/bin/polybar-refresh.sh

### ISSUE THREAD

**Issue by leglopy** [knazarov/dotfiles#2]
Thanks for sharing your configuration, it's really useful ! 
I was looking at the skhd config file https://github.com/knazarov/dotfiles/blob/master/skhd/skhdrc but it seems that script `/usr/local/bin/polybar-refresh.sh` is not included in your repository, could you add it to be able to switch space ?

**Comment by knazarov** [comment]
@leglopy Hi and thanks for your interest!

At the moment I don’t have my computer at hand. I’ve moved to another country and still wait for my stuff to get shipped.
What you can do though is something along the following lines:

```sh
osascript -e 'tell application "Übersicht" to refresh widget id "left-bar"'
```

or if that doesn’t work, use `polybar-left-bar` instead of `left-bar`. Please let me know if it work for you!

**Comment by leglopy** [comment]
@knazarov Sorry for late response. Thanks for your help and the youtube video it was exactly what I was looking for. I use your solution https://github.com/leglopy/dotfiles/blob/main/scripts/refreshPolybar.sh and it is working fine. I also personalized your polybar with another colorscheme https://github.com/leglopy/dotfiles/blob/main/images/polybar-tokyonight.png It was not that easy to set up all for the first time overall with a mac m1 but really happy of the result. Still a long way to improve my configs files (nvim plugins/skhdrc...) I am also considering to try to add my next meeting in the polybar with color changing (time). And automatically scrap the zoom link to open it with a shortcut. It's really annoying the experience notification open 15 mins before => need to keep it here => check time => open the calendar => look at the link => open it.

**Comment by wolves** [comment]
I have also relied a lot on your videos and GitHub to configure my system and came here looking for this exact script. Thank you a bunch for contributing. Its really helpful content. Cheers!

**Comment by knazarov** [comment]
Added the missing file: https://github.com/knazarov/dotfiles/blob/master/bin/polybar-refresh.sh

**Comment by knazarov** [comment]
The difference was the name of the widget. You basically need this:

```sh
osascript -e 'tell application "Übersicht" to refresh widget id "polybar-left-bar-coffee"'
```
